In [ ]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')

Step 1: Load and Read the healthcare-stroke-data.csv data from Github URL into a Pandas DataFrame.

In [ ]:
# Read the healthcare-stroke-data CSV file from URL into a Pandas DataFrame
url = 'https://raw.githubusercontent.com/GeorgeSKalad/Project-4-Stroke-Prediction-/main/Resources/healthcare-stroke-data.csv'
df = pd.read_csv(url)
# Review the DataFrame
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
# Convert all categorical columns in the DataFrame to numeric values.

# Convert the 'gender' column to a numeric value
df['gender'] = df['gender'].astype('category').cat.codes
# Convert the 'age' column to a numeric value
df['age'] = df['age'].astype('int')
# Convert the 'hypertension' column to a numeric value
df['hypertension'] = df['hypertension'].astype('int')
# Convert the 'heart_disease' column to a numeric value
df['heart_disease'] = df['heart_disease'].astype('int')
# Convert the 'ever_married' column to a numeric value
df['ever_married'] = df['ever_married'].astype('category').cat.codes
# Convert the 'work_type' column to a numeric value
df['work_type'] = df['work_type'].astype('category').cat.codes
# Convert the 'Residence_type' column to a numeric value
df['Residence_type'] = df['Residence_type'].astype('category').cat.codes
# Convert the 'avg_glucose_level' column to a numeric value
df['avg_glucose_level'] = df['avg_glucose_level'].astype('float')
# Convert the 'bmi' column to a numeric value
df['bmi'] = df['bmi'].astype('float')
# Convert the 'smoking_status' column to a numeric value
df['smoking_status'] = df['smoking_status'].astype('category').cat.codes
# Print the converted data
print(df)

         id  gender  age  hypertension  heart_disease  ever_married  \
0      9046       1   67             0              1             1   
1     51676       0   61             0              0             1   
2     31112       1   80             0              1             1   
3     60182       0   49             0              0             1   
4      1665       0   79             1              0             1   
...     ...     ...  ...           ...            ...           ...   
5105  18234       0   80             1              0             1   
5106  44873       0   81             0              0             1   
5107  19723       0   35             0              0             1   
5108  37544       1   51             0              0             1   
5109  44679       0   44             0              0             1   

      work_type  Residence_type  avg_glucose_level   bmi  smoking_status  \
0             2               1             228.69  36.6               

In [ ]:
# Drop rows with NaN values
df_cleaned = df.dropna()
print(df_cleaned)


         id  gender  age  hypertension  heart_disease  ever_married  \
0      9046       1   67             0              1             1   
2     31112       1   80             0              1             1   
3     60182       0   49             0              0             1   
4      1665       0   79             1              0             1   
5     56669       1   81             0              0             1   
...     ...     ...  ...           ...            ...           ...   
5104  14180       0   13             0              0             0   
5106  44873       0   81             0              0             1   
5107  19723       0   35             0              0             1   
5108  37544       1   51             0              0             1   
5109  44679       0   44             0              0             1   

      work_type  Residence_type  avg_glucose_level   bmi  smoking_status  \
0             2               1             228.69  36.6               

Step 2: Create the labels set (y) from the “stroke” column, and then create the features (X) DataFrame from the remaining columns.

In [ ]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df_cleaned["stroke"].values

# Separate the X variable, the features
X = df_cleaned.drop(columns="stroke").values

In [ ]:
# Review the y variable Series
print(y)

[1 1 1 ... 0 0 0]


In [ ]:
# Review the X variable DataFrame
X

array([[9.0460e+03, 1.0000e+00, 6.7000e+01, ..., 2.2869e+02, 3.6600e+01,
        1.0000e+00],
       [3.1112e+04, 1.0000e+00, 8.0000e+01, ..., 1.0592e+02, 3.2500e+01,
        2.0000e+00],
       [6.0182e+04, 0.0000e+00, 4.9000e+01, ..., 1.7123e+02, 3.4400e+01,
        3.0000e+00],
       ...,
       [1.9723e+04, 0.0000e+00, 3.5000e+01, ..., 8.2990e+01, 3.0600e+01,
        2.0000e+00],
       [3.7544e+04, 1.0000e+00, 5.1000e+01, ..., 1.6629e+02, 2.5600e+01,
        1.0000e+00],
       [4.4679e+04, 0.0000e+00, 4.4000e+01, ..., 8.5280e+01, 2.6200e+01,
        0.0000e+00]])

Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.


In [ ]:
# Check the balance of target values
print(y)

[1 1 1 ... 0 0 0]


In [ ]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    random_state=1)

## Create a Logistic Regression Model with the Original Data

In [ ]:
# Import Logistic Regression module
from sklearn.linear_model import LogisticRegression

# Create a Logistic Regression model
model = LogisticRegression(random_state=1)




In [ ]:
# Fit the model to the training data
model.fit(X_train, y_train)



LogisticRegression(random_state=1)

In [ ]:
# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate balanced accuracy
balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
print(f"Balanced Accuracy: {balanced_accuracy:.2f}")

# Generate a confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Generate a classification report
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_rep)

Balanced Accuracy: 0.51
Confusion Matrix:
[[1169    1]
 [  57    1]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.98      1170
           1       0.50      0.02      0.03        58

    accuracy                           0.95      1228
   macro avg       0.73      0.51      0.50      1228
weighted avg       0.93      0.95      0.93      1228



In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 6

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 8)                 96        
                                                                 
 dense_10 (Dense)            (None, 6)                 54        
                                                                 
 dense_11 (Dense)            (None, 1)                 7         
                                                                 
Total params: 157 (628.00 Byte)
Trainable params: 157 (628.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# Compile the model and train over more than 100 epochs
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
116/116 [==============================] - 1s 2ms/step - loss: 0.6658 - accuracy: 0.6542
Epoch 2/100
116/116 [==============================] - 0s 2ms/step - loss: 0.3626 - accuracy: 0.9530
Epoch 3/100
116/116 [==============================] - 0s 2ms/step - loss: 0.2433 - accuracy: 0.9590
Epoch 4/100
116/116 [==============================] - 0s 2ms/step - loss: 0.1913 - accuracy: 0.9590
Epoch 5/100
116/116 [==============================] - 0s 2ms/step - loss: 0.1684 - accuracy: 0.9590
Epoch 6/100
116/116 [==============================] - 0s 2ms/step - loss: 0.1582 - accuracy: 0.9590
Epoch 7/100
116/116 [==============================] - 0s 2ms/step - loss: 0.1528 - accuracy: 0.9590
Epoch 8/100
116/116 [==============================] - 0s 2ms/step - loss: 0.1497 - accuracy: 0.9590
Epoch 9/100
116/116 [==============================] - 0s 3ms/step - loss: 0.1474 - accuracy: 0.9590
Epoch 10/100
116/116 [==============================] - 0s 3ms/step - loss: 0.1457 - accura

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

39/39 - 0s - loss: 0.1632 - accuracy: 0.9528 - 317ms/epoch - 8ms/step
Loss: 0.1631903499364853, Accuracy: 0.9527687430381775


In [ ]:
nn.save("StrokePrediction.h5")